const productsData=[
  {
    id: '1',
    name: 'Reebok Tshirt Item 1',
    brand: 'Reebok',
    category: 'tshirt',
    description: 'Elevate Your Shoe Game',
    original_price: 16635,
    rating: '4.2',
    // no_of_reviews: 2339,
    no_of_ratings: 19223,
    discount: '54.17%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '2',
    name: 'Puma Tshirt Item 2',
    brand: 'Puma',
    category: 'tshirt',
    description: 'Dapper Denim for Urban Souls',
    original_price: 9989,
    rating: '2.5',
    no_of_reviews: 1309,
    no_of_ratings: 25850,
    discount: '87.00%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '3',
    name: 'Converse Tshirt Item 3',
    brand: 'Converse',
    category: 'tshirt',
    description: 'Elevate Your Look with Shoes',
    original_price: 10637,
    rating: '1.1',
    no_of_reviews: 8173,
    no_of_ratings: 36413,
    discount: '65.53%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '4',
    name: 'Nike Tshirt Item 4',
    brand: 'Nike',
    category: 'tshirt',
    description: 'Precision in Every Tick',
    original_price: 5042,
    rating: '2.4',
    no_of_reviews: 4361,
    no_of_ratings: 36631,
    discount: '74.78%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '5',
    name: 'Reebok Tshirt Item 5',
    brand: 'Reebok',
    category: 'tshirt',
    description: 'Simplicity Redefined in Denim',
    original_price: 12509,
    rating: '2.9',
    no_of_reviews: 4550,
    no_of_ratings: 43164,
    discount: '52.77%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '6',
    name: 'Nike Tshirt Item 6',
    brand: 'Nike',
    category: 'tshirt',
    description: 'Precision in Every Tick',
    original_price: 17018,
    rating: '2.4',
    no_of_reviews: 3034,
    no_of_ratings: 46601,
    discount: '32.54%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '7',
    name: 'Puma Tshirt Item 7',
    brand: 'Puma',
    category: 'tshirt',
    description: 'Casual Elegance for the Bold',
    original_price: 10473,
    rating: '1.8',
    no_of_reviews: 8373,
    no_of_ratings: 3130,
    discount: '5.06%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '8',
    name: 'Puma Tshirt Item 8',
    brand: 'Puma',
    category: 'tshirt',
    description: 'Chic Denim Upgrade for You',
    original_price: 18746,
    rating: '3.9',
    no_of_reviews: 3874,
    no_of_ratings: 45282,
    discount: '19.51%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '9',
    name: 'Adidas Tshirt Item 9',
    brand: 'Adidas',
    category: 'tshirt',
    description: 'Timeless Classic for Your Wrist',
    original_price: 12374,
    rating: '4.7',
    no_of_reviews: 2741,
    no_of_ratings: 29501,
    discount: '2.99%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '10',
    name: 'Nike Tshirt Item 10',
    brand: 'Nike',
    category: 'tshirt',
    description: 'Urban Charm in Every Stitch',
    original_price: 8145,
    rating: '2.5',
    no_of_reviews: 8330,
    no_of_ratings: 35414,
    discount: '9.63%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '11',
    name: 'Fastrack Tshirt Item 11',
    brand: 'Fastrack',
    category: 'tshirt',
    description: 'Urban Charm in Every Stitch',
    original_price: 17098,
    rating: '4.9',
    no_of_reviews: 3820,
    no_of_ratings: 1188,
    discount: '46.07%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '12',
    name: 'Nike Tshirt Item 12',
    brand: 'Nike',
    category: 'tshirt',
    description: 'Street-Ready Tee, Your Way',
    original_price: 10710,
    rating: '4.7',
    no_of_reviews: 4460,
    no_of_ratings: 46096,
    discount: '67.87%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '13',
    name: 'Fastrack Tshirt Item 13',
    brand: 'Fastrack',
    category: 'tshirt',
    description: 'Timeless Classic for Your Wrist',
    original_price: 19332,
    rating: '3.9',
    no_of_reviews: 6083,
    no_of_ratings: 5202,
    discount: '48.91%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/s-cmb-po2-dab-wynk-smartees-original-imagm5vhumtz8epz.webp'
  },
  {
    id: '14',
    name: 'Converse Watch Item 14',
    brand: 'Converse',
    category: 'watch',
    description: 'Sleek Timepiece for Modern Style',
    original_price: 15296,
    rating: '1.1',
    no_of_reviews: 8470,
    no_of_ratings: 4947,
    discount: '89.12%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '15',
    name: 'Converse Watch Item 15',
    brand: 'Converse',
    category: 'watch',
    description: 'Dapper Denim for Urban Souls',
    original_price: 9847,
    rating: '4.6',
    no_of_reviews: 4318,
    no_of_ratings: 39122,
    discount: '26.37%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '16',
    name: 'Puma Watch Item 16',
    brand: 'Puma',
    category: 'watch',
    description: 'Elevate Your Shoe Game',
    original_price: 5501,
    rating: '4.3',
    no_of_reviews: 7162,
    no_of_ratings: 19711,
    discount: '2.93%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '17',
    name: 'Adidas Watch Item 17',
    brand: 'Adidas',
    category: 'watch',
    description: 'Timeless Appeal, Modern Design',
    original_price: 5996,
    rating: '3.5',
    no_of_reviews: 1070,
    no_of_ratings: 696,
    discount: '71.28%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '18',
    name: 'Converse Watch Item 18',
    brand: 'Converse',
    category: 'watch',
    description: 'Step Into Comfort and Style',
    original_price: 6762,
    rating: '4.4',
    no_of_reviews: 947,
    no_of_ratings: 12600,
    discount: '34.56%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '19',
    name: 'Puma Watch Item 19',
    brand: 'Puma',
    category: 'watch',
    description: 'Elevate Your Shoe Game',
    original_price: 7477,
    rating: '1.3',
    no_of_reviews: 4625,
    no_of_ratings: 17470,
    discount: '49.17%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '20',
    name: 'Converse Watch Item 20',
    brand: 'Converse',
    category: 'watch',
    description: 'Chic Denim Upgrade for You',
    original_price: 16687,
    rating: '3.0',
    no_of_reviews: 8892,
    no_of_ratings: 18593,
    discount: '18.08%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '21',
    name: 'Adidas Watch Item 21',
    brand: 'Adidas',
    category: 'watch',
    description: 'Simplicity Redefined in Denim',
    original_price: 6049,
    rating: '3.1',
    no_of_reviews: 3548,
    no_of_ratings: 37628,
    discount: '73.20%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '22',
    name: 'Adidas Watch Item 22',
    brand: 'Adidas',
    category: 'watch',
    description: 'Modern Charm Wrapped in Denim',
    original_price: 5949,
    rating: '2.1',
    no_of_reviews: 8404,
    no_of_ratings: 4436,
    discount: '18.13%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '23',
    name: 'Nike Watch Item 23',
    brand: 'Nike',
    category: 'watch',
    description: 'Effortless Style with Every Step',
    original_price: 6864,
    rating: '4.5',
    no_of_reviews: 2128,
    no_of_ratings: 36576,
    discount: '12.95%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '24',
    name: 'Adidas Watch Item 24',
    brand: 'Adidas',
    category: 'watch',
    description: 'Timeless Classic for Your Wrist',
    original_price: 14536,
    rating: '4.3',
    no_of_reviews: 4597,
    no_of_ratings: 17,
    discount: '81.28%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '25',
    name: 'Reebok Watch Item 25',
    brand: 'Reebok',
    category: 'watch',
    description: 'Vibrant Tee for Street Chic',
    original_price: 9979,
    rating: '3.1',
    no_of_reviews: 691,
    no_of_ratings: 39564,
    discount: '54.31%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '26',
    name: 'Puma Watch Item 26',
    brand: 'Puma',
    category: 'watch',
    description: 'Urban Charm in Every Stitch',
    original_price: 12699,
    rating: '4.5',
    no_of_reviews: 8239,
    no_of_ratings: 42219,
    discount: '77.25%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/g715-casio-original-imag5jsrbzfjqmeb.webp'
  },
  {
    id: '27',
    name: 'Adidas Shoes Item 27',
    brand: 'Adidas',
    category: 'shoes',
    description: 'Step Out in Style and Comfort',
    original_price: 11290,
    rating: '4.4',
    no_of_reviews: 6499,
    no_of_ratings: 23492,
    discount: '17.24%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '28',
    name: 'Reebok Shoes Item 28',
    brand: 'Reebok',
    category: 'shoes',
    description: 'Precision in Every Tick',
    original_price: 12479,
    rating: '3.5',
    no_of_reviews: 278,
    no_of_ratings: 19264,
    discount: '1.88%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '29',
    name: 'Puma Shoes Item 29',
    brand: 'Puma',
    category: 'shoes',
    description: 'Vibrant Tee for Street Chic',
    original_price: 15404,
    rating: '4.5',
    no_of_reviews: 3628,
    no_of_ratings: 24640,
    discount: '75.38%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '30',
    name: 'Puma Shoes Item 30',
    brand: 'Puma',
    category: 'shoes',
    description: 'Step Into Comfort and Style',
    original_price: 5012,
    rating: '1.9',
    no_of_reviews: 8542,
    no_of_ratings: 44281,
    discount: '29.42%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '31',
    name: 'Reebok Shoes Item 31',
    brand: 'Reebok',
    category: 'shoes',
    description: 'Step Into Comfort and Style',
    original_price: 14761,
    rating: '1.5',
    no_of_reviews: 4792,
    no_of_ratings: 18184,
    discount: '64.02%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '32',
    name: 'Nike Shoes Item 32',
    brand: 'Nike',
    category: 'shoes',
    description: 'Luxurious Denim for Trendsetters',
    original_price: 19626,
    rating: '4.7',
    no_of_reviews: 6760,
    no_of_ratings: 46622,
    discount: '81.18%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '33',
    name: 'Adidas Shoes Item 33',
    brand: 'Adidas',
    category: 'shoes',
    description: 'Sleek Timepiece for Modern Style',
    original_price: 18984,
    rating: '3.6',
    no_of_reviews: 309,
    no_of_ratings: 14747,
    discount: '81.30%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '34',
    name: 'Adidas Shoes Item 34',
    brand: 'Adidas',
    category: 'shoes',
    description: 'Urban Charm in Every Stitch',
    original_price: 6291,
    rating: '2.6',
    no_of_reviews: 9269,
    no_of_ratings: 30255,
    discount: '85.10%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '35',
    name: 'Converse Shoes Item 35',
    brand: 'Converse',
    category: 'shoes',
    description: 'Stylish Steps, All Day Comfort',
    original_price: 8985,
    rating: '2.5',
    no_of_reviews: 538,
    no_of_ratings: 22705,
    discount: '9.53%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '36',
    name: 'Fastrack Shoes Item 36',
    brand: 'Fastrack',
    category: 'shoes',
    description: 'Casual Elegance Redefined',
    original_price: 8012,
    rating: '2.3',
    no_of_reviews: 5474,
    no_of_ratings: 19225,
    discount: '25.67%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '37',
    name: 'Adidas Shoes Item 37',
    brand: 'Adidas',
    category: 'shoes',
    description: 'Denim Love, Every Stitch Matters',
    original_price: 5456,
    rating: '4.9',
    no_of_reviews: 2167,
    no_of_ratings: 8800,
    discount: '13.98%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '38',
    name: 'Adidas Shoes Item 38',
    brand: 'Adidas',
    category: 'shoes',
    description: 'Unleash Your Casual Vibe',
    original_price: 17158,
    rating: '3.3',
    no_of_reviews: 8511,
    no_of_ratings: 12910,
    discount: '35.06%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '39',
    name: 'Nike Shoes Item 39',
    brand: 'Nike',
    category: 'shoes',
    description: 'Urban Charm in Every Stitch',
    original_price: 17933,
    rating: '4.0',
    no_of_reviews: 8715,
    no_of_ratings: 4380,
    discount: '66.23%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/8-5089-8-server-brown-original-imagrnqaygfghm3g.webp'
  },
  {
    id: '40',
    name: 'Reebok Jeans Item 40',
    brand: 'Reebok',
    category: 'jeans',
    description: 'Stylish Steps, All Day Comfort',
    original_price: 5112,
    rating: '4.8',
    no_of_reviews: 9218,
    no_of_ratings: 5279,
    discount: '12.33%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '41',
    name: 'Fastrack Jeans Item 41',
    brand: 'Fastrack',
    category: 'jeans',
    description: 'Bold and Comfy Everyday Tee',
    original_price: 5405,
    rating: '4.7',
    no_of_reviews: 2189,
    no_of_ratings: 21402,
    discount: '43.72%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '42',
    name: 'Puma Jeans Item 42',
    brand: 'Puma',
    category: 'jeans',
    description: 'Casual Chic Tee for All',
    original_price: 5074,
    rating: '4.5',
    no_of_reviews: 7145,
    no_of_ratings: 4713,
    discount: '49.92%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '43',
    name: 'Reebok Jeans Item 43',
    brand: 'Reebok',
    category: 'jeans',
    description: 'Vibrant Tee for Street Chic',
    original_price: 19934,
    rating: '3.6',
    no_of_reviews: 2998,
    no_of_ratings: 40871,
    discount: '52.65%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '44',
    name: 'Converse Jeans Item 44',
    brand: 'Converse',
    category: 'jeans',
    description: 'Step Into Comfort and Style',
    original_price: 13408,
    rating: '1.1',
    no_of_reviews: 5378,
    no_of_ratings: 42357,
    discount: '19.74%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '45',
    name: 'Puma Jeans Item 45',
    brand: 'Puma',
    category: 'jeans',
    description: 'Vibrant Tee for Street Chic',
    original_price: 14515,
    rating: '3.1',
    no_of_reviews: 4609,
    no_of_ratings: 48432,
    discount: '12.96%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '46',
    name: 'Nike Jeans Item 46',
    brand: 'Nike',
    category: 'jeans',
    description: 'Distinctive Denim Elegance',
    original_price: 12008,
    rating: '3.8',
    no_of_reviews: 8079,
    no_of_ratings: 27064,
    discount: '59.81%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '47',
    name: 'Fastrack Jeans Item 47',
    brand: 'Fastrack',
    category: 'jeans',
    description: 'Casual Chic Tee for All',
    original_price: 19100,
    rating: '3.2',
    no_of_reviews: 3452,
    no_of_ratings: 47967,
    discount: '45.19%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '48',
    name: 'Puma Jeans Item 48',
    brand: 'Puma',
    category: 'jeans',
    description: 'Dapper Denim for Urban Souls',
    original_price: 11879,
    rating: '4.0',
    no_of_reviews: 9754,
    no_of_ratings: 25879,
    discount: '64.80%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '49',
    name: 'Adidas Jeans Item 49',
    brand: 'Adidas',
    category: 'jeans',
    description: 'Simplicity Redefined in Denim',
    original_price: 13514,
    rating: '2.0',
    no_of_reviews: 6911,
    no_of_ratings: 43778,
    discount: '45.69%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '50',
    name: 'Nike Jeans Item 50',
    brand: 'Nike',
    category: 'jeans',
    description: 'Sleek Timepiece for Modern Style',
    original_price: 18270,
    rating: '1.5',
    no_of_reviews: 5027,
    no_of_ratings: 31297,
    discount: '14.97%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '51',
    name: 'Nike Jeans Item 51',
    brand: 'Nike',
    category: 'jeans',
    description: 'Timeless Classic for Your Wrist',
    original_price: 9239,
    rating: '4.1',
    no_of_reviews: 4287,
    no_of_ratings: 47524,
    discount: '11.52%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  },
  {
    id: '52',
    name: 'Adidas Jeans Item 52',
    brand: 'Adidas',
    category: 'jeans',
    description: 'Elevate Your Look with Shoes',
    original_price: 15379,
    rating: '4.8',
    no_of_reviews: 3884,
    no_of_ratings: 41257,
    discount: '77.75%',
    img_url: '/home/beehyv/LearnReact/matchlessgifts/src/assets/-original-imagt6zh6gsq2hw8.webp'
  }
];

export default productsData;


export const calcPrice = (obj) => {
  const originalPrice = parseInt(obj.original_price);
  const discountPercentage = parseInt(obj.discount);
  const discountedPrice =
    originalPrice - (originalPrice * discountPercentage) / 100;
  const roundedDiscountedPrice = Math.round(discountedPrice);
  return roundedDiscountedPrice;
};

export const sortProducts=(productsData, sortByOption)=>{
  switch (sortByOption) {
    case "Price:Low to High":
      return productsData.slice().sort((a, b) => calcPrice(a) - calcPrice(b));
    case "Price:High to Low":
      return productsData.slice().sort((a, b) =>calcPrice(b) - calcPrice(a));
    case "Average Customer Review":
      return productsData.slice().sort((a, b) => b.rating - a.rating);
    case "None":
    default:
      return productsData.slice(); 
  }
}